### ISSUE TITLE
documentation for  --recoid and --scanid unclear

### ISSUE THREAD

**Issue by gdevenyi** [BrkRaw/bruker#3]
Typically, I would except to be able to extract single scan by some sort of number in the scan order:
```
$ brkraw info raw
Paravision 5.1
--------------
UserAccount:    galdan
Date:           2020-01-31
Researcher:     MCH_DEV_PHT_001
Subject ID:     20200131_MCH_DEV_PHT_001
Session ID:     dev
Study ID:       1
Date of Birth:  None
Sex:            male
Weight:         5 kg
Subject Type:   Human
Position:       Supine          Entry:  HeadFirst

[ScanID]        Sequence::Protocol::[Parameters]
[001]   FLASH (pvm)::01-TriPilot-multi::
        [ TR: 200 ms, TE: 3 ms, pixelBW: 500.80 Hz, FlipAngle: 30 degree]
    [01] dim: 2D, matrix_size: 256 x 256 x 15, fov_size: 40 x 40 (unit:mm)
         spatial_resol: 0.156 x 0.156 x 1.000 (unit:mm), temporal_resol: 25600.000 (unit:msec)
[002]   FLASH (pvm)::exvivoDanFLASH::
        [ TR: 21.47 ms, TE: 5.11 ms, pixelBW: 96.90 Hz, FlipAngle: 20 degree]
    [01] dim: 3D, matrix_size: 228 x 258 x 130, fov_size: 15.96 x 18.06 x 9.1 (unit:mm)
         spatial_resol: 0.070 x 0.070 x 0.070 (unit:mm), temporal_resol: 1920266.000 (unit:msec)

$ $ brkraw tonii --scanid 1 raw
[Warning]::'1'
```

I don't know what --recoid and --scanid refer to?

**Comment by dvm-shlee** [comment]
Hi @gdevenyi 
Sorry about the unclear documentation for the single file conversion and also thank you for reporting a bug.
The --scanid and --recoid are the options to specify the Scan ID and Reconstruction ID as you expected. 

The reason you cannot get it is because of the bug that the input passed as a string value
while the python API of the conversion only accepts integer.

I've fixed the bug so it will work normally from 0.3.3 rc2 version.

Thank you!

**Comment by gdevenyi** [comment]
The error has been fixed, however --scanid annd --recoid haven't had their documentation updated to indicate what they refer to.

**Comment by dvm-shlee** [comment]
@gdevenyi Thank you for your comments on it. Regarding the documentation, I just made updated it on https://brkraw.github.io but are you meaning the documentation on the usage of CLI?

**Comment by gdevenyi** [comment]
Yes, I'm referring to the CLI

**Comment by dvm-shlee** [comment]
Thank you for clarifying. I will update the documentation for the next update!

**Comment by dvm-shlee** [comment]
@gdevenyi the help string for --scanid and --recoid are updated on CLI as below.
If these are still not clear, could you make some suggestions? (actually not good at this kind of writing, unfortunately.... :-(

--scanid: Scan ID, option to specify a particular scan to convert.
--recoid: RECO ID (default=1), option to specify a particular reco to convert

**Comment by gdevenyi** [comment]
Thanks, this is much improved.
For this:
```
--recoid: RECO ID (default=1), option to specify a particular reco to convert
```
The help should use the full name for reco, which I *think* is reconstruction?

**Comment by dvm-shlee** [comment]
@gdevenyi Thank you for your suggestion! 
Then maybe we can try..
```--recoid: RECO ID (default=1), option to specify a particular reconstruction id code to convert```
or
```--recoid: RECO ID (default=1), option to specify a particular method of reconstruction to convert```
Do you have any preferences?

**Comment by gdevenyi** [comment]
I think I prefer:
```
--recoid: RECO ID (default=1), option to specify a particular reconstruction id to convert
```

**Comment by dvm-shlee** [comment]
@gdevenyi I update your suggestion to the help document on CLI.
I will close this issue, Thank you!
